version: "3.8"

services:
  minio:
    image: minio/minio:RELEASE.2024-08-17T01-24-54Z
    entrypoint:
      - /bin/sh
      - -c
      - |
        export MINIO_ROOT_USER=$$(cat /run/secrets/minio_username); \
        export MINIO_ROOT_PASSWORD=$$(cat /run/secrets/minio_password); \
        exec /usr/bin/docker-entrypoint.sh server /data --address ":9000" --console-address ":9001"
    volumes:
      - minio_data:/data
    secrets:
      - minio_username
      - minio_password
    networks:
      - storage
      - traefik-public
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/minio/health/live || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.http.routers.minio-api.rule=Host(`${MINIO_API_DOMAIN}`)
        - traefik.http.routers.minio-api.entrypoints=websecure
        - traefik.http.routers.minio-api.tls=true
        - traefik.http.routers.minio-api.service=minio-api
        - traefik.http.services.minio-api.loadbalancer.server.port=9000
        - traefik.http.routers.minio-console.rule=Host(`${MINIO_CONSOLE_DOMAIN}`)
        - traefik.http.routers.minio-console.entrypoints=websecure
        - traefik.http.routers.minio-console.tls=true
        - traefik.http.routers.minio-console.service=minio-console
        - traefik.http.services.minio-console.loadbalancer.server.port=9001

networks:
  storage:
    driver: overlay
  traefik-public:
    external: true

volumes:
  minio_data:
    driver: local

secrets:
  minio_username:
    external: true
  minio_password:
    external: true
